export const types = [
	"approval",
	"favorability",
	"generic-ballot",
	"governor",
	"governor-recall",
	"house",
	"president-general",
	"president-primary-d",
	"president-primary-r",
	"senate",
]

export const codes = {
	"AL": "alabama",
	"AK": "alaska",
	"AR": "arkansas",
	"AS": "american-samoa",
	"AZ": "arizona",
	"CA": "california",
	"CO": "colorado",
	"CT": "connecticut",
	"DC": "district-of-columbia",
	"DE": "delaware",
	"FL": "florida",
	"GA": "georgia",
	"GU": "guam",
	"HI": "hawaii",
	"IA": "iowa",
	"ID": "idaho",
	"IL": "illinois",
	"IN": "indiana",
	"KS": "kansas",
	"KY": "kentucky",
	"LA": "louisiana",
	"ME": "maine",
	"MD": "maryland",
	"MA": "massachusetts",
	"MI": "michigan",
	"MN": "minnesota",
	"MO": "missouri",
	"MS": "mississippi",
	"MT": "montana",
	"NC": "north-carolina",
	"ND": "north-dakota",
	"NE": "nebraska",
	"NH": "new-hampshire",
	"NJ": "new-jersey",
	"NM": "new-mexico",
	"NV": "nevada",
	"NY": "new-york",
	"OH": "ohio",
	"OK": "oklahoma",
	"OR": "oregon",
	"PA": "pennsylvania",
	"PR": "puerto-rico",
	"RI": "rhode-island",
	"SC": "south-carolina",
	"SD": "south-dakota",
	"TN": "tennessee",
	"TX": "texas",
	"UT": "utah",
	"VA": "virginia",
	"VI": "us-virgin-islands",
	"VT": "vermont",
	"WA": "washington",
	"WI": "wisconsin",
	"WV": "west-virginia",
	"WY": "wyoming",
}